// <auto-generated />
namespace DemoLabWindowsForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class BoSungQuanHeBangGhe_ChiTiet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BoSungQuanHeBangGhe_ChiTiet));
        
        string IMigrationMetadata.Id
        {
            get { return "201910050247020_BoSungQuanHeBangGhe_ChiTiet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
